use std::path::PathBuf;
use crate::adb::{require_success, Adb, AdbCommand, AppOpMode, BridgeOperation, DeviceOperation, Fingerprint, RecoveryEnvelope, Serial};
use crate::device::catalog::recovery_envelope;
use crate::policy::Operation;
use crate::recovery::{mirror::MirrorStore, shared_copy};
use super::DeviceFailure;

pub struct AdbTransaction<'a, A: Adb> { pub adb: &'a mut A, pub serial: Serial, pub fingerprint: Fingerprint, pub source: PathBuf }
impl<'a, A: Adb> AdbTransaction<'a, A> { pub fn new(adb: &'a mut A, serial: Serial, fingerprint: Fingerprint, source: PathBuf) -> Self { Self { adb, serial, fingerprint, source } } fn command(&mut self, operation: DeviceOperation) -> Result<String, DeviceFailure> { require_success(self.adb.execute(AdbCommand::Device { serial: self.serial.clone(), operation }).map_err(|_| DeviceFailure::Disconnect)?).map(|o| o.stdout().into()).map_err(|_| DeviceFailure::Command) } }
impl<A: Adb> MirrorStore for AdbTransaction<'_, A> { type Error=DeviceFailure; fn write_private(&mut self,value:&str)->Result<(),Self::Error>{let envelope=RecoveryEnvelope::parse(value).map_err(|_|DeviceFailure::Inconsistent)?;self.command(DeviceOperation::Bridge(BridgeOperation::WriteEnvelope{device_serial:self.serial.clone(),fingerprint:self.fingerprint.clone(),envelope}))?;Ok(())} fn write_shared(&mut self,value:&str)->Result<(),Self::Error>{std::fs::write(&self.source,value).map_err(|_|DeviceFailure::Inconsistent)?;shared_copy::write_from(self.adb,&self.serial,&self.source).map_err(|_|DeviceFailure::Command)} fn read_private(&mut self)->Result<Option<String>,Self::Error>{let output=self.command(DeviceOperation::Bridge(BridgeOperation::ReadEnvelope{device_serial:self.serial.clone(),fingerprint:self.fingerprint.clone()}))?;Ok(recovery_envelope(&output).map_err(|_|DeviceFailure::Inconsistent)?)} fn read_shared(&mut self)->Result<Option<String>,Self::Error>{let output=self.command(DeviceOperation::ReadDestination(shared_copy::destination()))?;Ok(Some(output))} fn delete_private(&mut self)->Result<(),Self::Error>{Err(DeviceFailure::Inconsistent)} fn delete_shared(&mut self)->Result<(),Self::Error>{Err(DeviceFailure::Inconsistent)} }
impl<A: Adb> super::ApplyDevice for AdbTransaction<'_, A> { fn mutate(&mut self,op:&Operation)->Result<(),DeviceFailure>{match op { Operation::Suspend{package,user,suspended}=>{self.command(DeviceOperation::Suspend{package:package.clone(),user:*user,suspended:*suspended})?;} Operation::AppOp{package,user,app_op,mode}=>{self.command(DeviceOperation::AppOpSet{package:package.clone(),user:*user,app_op:app_op.clone(),mode:*mode})?;} Operation::Home{component}=>{self.command(DeviceOperation::HomeSelect(component.clone()))?;} Operation::LauncherPolicy{..}|Operation::Verify|Operation::Maintenance{..}=>()};Ok(())} fn verified(&mut self,op:&Operation)->Result<bool,DeviceFailure>{match op { Operation::Suspend{package,user,suspended}=>Ok(self.command(DeviceOperation::PackageState{package:package.clone(),user:*user})?.contains(&format!("suspended={suspended}"))), Operation::AppOp{package,user,app_op,mode}=>{let wanted=match mode{AppOpMode::Default=>"default",AppOpMode::Allow=>"allow",AppOpMode::Ignore=>"ignore"};Ok(self.command(DeviceOperation::AppOpGet{package:package.clone(),user:*user,app_op:app_op.clone()})?.lines().any(|line| { let Some(rest)=line.trim().strip_prefix(&format!("{}:",app_op.as_str())) else { return false }; rest.trim().split(|c: char| c==';' || c.is_whitespace()).next()==Some(wanted) }))} Operation::Home{component}=>Ok(self.command(DeviceOperation::HomeResolve)?.trim()==component.as_str()), Operation::LauncherPolicy{..}|Operation::Verify|Operation::Maintenance{..}=>Ok(true)}} fn chooser(&mut self)->Result<(),DeviceFailure>{self.command(DeviceOperation::HomeChooser)?;Ok(())} }




